### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by SaintLogos1234** [yolomax/rru-reid#2]
May I ask when the complete code will be released

**Comment by yolomax** [comment]
Thank you very much for your concern about our work. The complete code will be integrated directly into the repository [person-reid-lib](https://github.com/yolomax/person-reid-lib), which is still under way. I'm working as an intern in the company, so it's not very convenient for me to test and upload the code. I will finish it as soon as possible.

**Comment by SaintLogos1234** [comment]
Thank you for your reply

**Comment by yolomax** [comment]
Hi. The code is already available in [person-reid-lib](https://github.com/yolomax/person-reid-lib).

**Comment by SaintLogos1234** [comment]
I have read your paper carefully again, and I am very interested in your following two points:channel avg pooling and spatial avg pooling, Is this your own creation or  refering from others? Where are the specific implementation details of these modules reflected in the code

**Comment by yolomax** [comment]
This is a common operation in many papers. The implementation details are in line [44](https://github.com/yolomax/rru-reid/blob/b0822a611eb85ce1baa3afe27f54fb6af37b3170/rru.py#L44) and [49](https://github.com/yolomax/rru-reid/blob/b0822a611eb85ce1baa3afe27f54fb6af37b3170/rru.py#L49) of rru.py

**Comment by SaintLogos1234** [comment]
Thank you
